export const LOGOUT = 'LOGOUT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SHOW_ORGANIZATION = 'SHOW_ORGANIZATION'
export const DELETE_ORGANIZATION_FILE = 'DELETE_ORGANIZATION_FILE'
export const GET_USER_NAV_ORGANIZATION_SUBSCRIBE_FILES = 'GET_USER_NAV_ORGANIZATION_SUBSCRIBE_FILES'

export const SHOW_USER = 'SHOW_USER'
export const SHOW_SUBSCRIBE = 'SHOW_SUBSCRIBE'
export const GET_USER_NAV_SUBSCRIBE = 'GET_USER_NAV_SUBSCRIBE'
export const GET_CURRENCIES = 'GET_CURRENCIES'
export const DELETE_SUBSCRIBE_PROJECT = 'DELETE_SUBSCRIBE_PROJECT'
export const GET_ORGANIZATIONS_USER_SUBSCRIBES = 'GET_ORGANIZATIONS_USER_SUBSCRIBES'
